### ISSUE TITLE
[Question] Usage of vkShade for emulators

### ISSUE THREAD

**Issue by AmyRoxwell** [ralgar/vkShade#11]
I wonder if you could use this for native Linux applications, like emulators, that support rendering using vulkan (Like PCSX2, Dolphin, duckstation, etc), I remember vkBasalt having some issues with native linux applications, so I wonder if this project would try to make it less of an issue so we can use shaders like "CRT-Royale" for standalone emulators.

**Comment by ralgar** [comment]
vkShade *shouldn't* have issues with native applications any more than it does with WINE/DXVK. At the end of the day, they all leverage the native Vulkan implementation. Granted, it's a very simple app, but I always do a basic smoke test against `vkcube` when I'm developing.

It's possible there are issues are related to that specific shader, as there *are* still problems with the ReShade implementation in both this project and vkBasalt.

I myself am not much into emulators these days, but I'd invite you to test it out and update this issue with your findings. I will do my best to fix any issues that are related to vkShade, so long as you can provide me with enough info to reliably reproduce them.

**Comment by AmyRoxwell** [comment]
> I don't believe vkShade should have issues with native applications any more than it does with WINE. They all leverage the native Vulkan implementation.
> 
> It's possible there are issues are related to that specific shader, as there _are_ still problems with the ReShade implementation in both this project and vkBasalt. Could possibly be an issue with the application's implementation of Vulkan as well.
> 
> I'm not much into emulators these days, but I'd invite you to test some things out and update this issue with your findings. I'll do my best to fix any issues that are related to vkShade, so long as you can provide me with enough info to reliably reproduce them. If you have any links to relevant issues in the vkBasalt repo, that would be helpful as well.

I will be testing on the upcoming days, thank you so much for the answer.
in the mean time, the only one report that I had seen on vkbasalt about crt-royale not working is this one:
https://github.com/DadSchoorse/vkBasalt/issues/223

**Comment by AmyRoxwell** [comment]
Alright, tried to run it with pcsx2, using only vulkan mode enabled and when trying to boot any game while using vkshade, it will crash the emulator.
[vkShade.log](https://github.com/ralgar/vkShade/files/12667303/vkShade.log)

The log doesnt really tell much tbh, tried without any shaders, with shaders but it will always result on the emulator crashing while trying to boot any game.

**Comment by ralgar** [comment]
Okay, first thing - line 5 of the log mentions that it couldn't load a ReShade preset. You *will* need to have a valid preset and at least one shader loaded, as there is currently a bug where the layer will crash if no effects are loaded at all (see #1). You can put a preset at `~/.config/vkShade/ReShade.ini`, and try running `vkcube` to make sure it's working as expected.

If it doesn't work after you have a preset configured, then post the log again. Also, please run the emulator from the command line and force the Vulkan validation layers, and post the output of that as well:

```
VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ENABLE_VKSHADE=1 pcsx2-qt
```

Finally, it would be helpful if you could post your preset as well, so that I can test with the same configuration.

**Comment by AmyRoxwell** [comment]
> Okay, first thing - line 5 of the log mentions that it couldn't load a ReShade preset. You _will_ need to have a valid preset and at least one shader loaded, as there is currently a bug where the layer will crash if no effects are loaded at all (see #1). You can put a preset at `~/.config/vkShade/ReShade.ini`, and try running `vkcube` to make sure it's working as expected.

> Finally, it would be helpful if you could post your preset as well, so that I can test with the same configuration.

Alright, how do I load a preset or how do I make a preset? is there a format I need to follow? Do I use an application to make said preset while loading the fxh files? I checked other shaders but they dont seem to have any kind of Preset file or ReShade.ini file on them...

**Comment by ralgar** [comment]
Okay, I've had a look into this properly, and for the time being it looks like this particular shader will **not** work unfortunately.

I'm not sure what is the exact version of the ReShade compiler that I inherited from vkBasalt but, based on the date of the commit, it would have to be version 4.6.1 or lower. CRT-Royale appears to be built on features introduced in ReShade 4.9. I briefly tried to get it running but, unsurprisingly, it throws a bunch of errors and then crashes:

```
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/helper-functions-and-macros.fxh(29, 8): error X3004: undeclared identifier or no matching intrinsic overload for 'tex2Dlod'
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 25): error X3000: syntax error: unexpected 'identifier', expected ','
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 25): error X3000: syntax error: unexpected 'identifier'
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 28): error X3000: syntax error: unexpected 'integral literal'
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 31): error X3000: syntax error: unexpected 'identifier'
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 34): error X3000: syntax error: unexpected 'integral literal'
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 37): error X3000: syntax error: unexpected 'identifier'
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale.fx(65, 1): warning X4576: 'preblurHorizPS': input parameter 'texcoord' semantic does not match vertex shader one
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale.fx(111, 1): warning X4576: 'approximateBloomVertPS': input parameter 'texcoord' semantic does not match vertex shader one
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale.fx(119, 1): warning X4576: 'approximateBloomHorizPS': input parameter 'texcoord' semantic does not match vertex shader one
vkShade err:   /opt/reshade-shaders/Shaders/crt-royale.fx(184, 1): warning X4576: 'applyComputedPhosphorMaskPS': input parameter 'texcoord' semantic does not match vertex shader one
zsh: segmentation fault (core dumped)  ENABLE_VKSHADE=1 vkcube
```

So it looks like, at the very least, use of this shader will have to wait until #6 is taken care of. Unfortunately updating the ReShade version is likely going to require a significant refactor of vkShade's code as well, so it will probably be some time before it's all sorted out.

---

As for your preset question, presets are standard ReShade presets, which are in the [INI file format](https://docs.fileformat.com/system/ini/). Often you will be able to find ready-to-go presets on the ReShade forums, or other sites such as NexusMods. Usually an individual preset is made for a specific game.

A fairly basic example looks like this:

```ini
PreprocessorDefinitions=
Techniques=Curves,Clarity
TechniqueSorting=Curves,Clarity

[Clarity.fx]
ClarityBlendIfDark=50
ClarityBlendIfLight=205
ClarityBlendMode=0
ClarityDarkIntensity=0.000000
ClarityLightIntensity=0.000000
ClarityOffset=50.000000
ClarityRadius=4
ClarityStrength=0.500000
ClarityViewBlendIfMask=0
ClarityViewMask=0

[Curves.fx]
Contrast=0.650000
Formula=1
Mode=0
```

The only required key-value pair is `TechniquesSorting`, which is how vkShade knows which shaders to load. The shader names that go in this field can be kind of a "gotcha", as they don't necessarily match the shader file name, they actually use the **technique name** which can be found in the shader's source code.

The sections below are how you actually configure each shader. The heading (`[Clarity.fx]` for example) corresponds directly to the file name of the shader. The key-value pairs underneath the heading correspond directly to the shader **uniforms**, which is just the technical term for a variable when dealing with shaders. You can also find these in the source code, and probably in the shader's documentation as well.

You don't *have* to configure the uniforms, but generally you will want to as the default settings are often either way too strong, or barely noticeable at all.

**Comment by AmyRoxwell** [comment]
> Okay, I've had a look into this properly, and for the time being it looks like this particular shader will **not** work unfortunately.
> 
> I'm not sure what is the exact version of the ReShade compiler that I inherited from vkBasalt but, based on the date of the commit, it would have to be version 4.6.1 or lower. CRT-Royale appears to be built on features introduced in ReShade 4.9. I briefly tried to get it running but, unsurprisingly, it throws a bunch of errors and then crashes:
> 
> ```
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/helper-functions-and-macros.fxh(29, 8): error X3004: undeclared identifier or no matching intrinsic overload for 'tex2Dlod'
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 25): error X3000: syntax error: unexpected 'identifier', expected ','
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 25): error X3000: syntax error: unexpected 'identifier'
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 28): error X3000: syntax error: unexpected 'integral literal'
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 31): error X3000: syntax error: unexpected 'identifier'
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 34): error X3000: syntax error: unexpected 'integral literal'
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale/shaders/../lib/bind-shader-params.fxh(148, 37): error X3000: syntax error: unexpected 'identifier'
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale.fx(65, 1): warning X4576: 'preblurHorizPS': input parameter 'texcoord' semantic does not match vertex shader one
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale.fx(111, 1): warning X4576: 'approximateBloomVertPS': input parameter 'texcoord' semantic does not match vertex shader one
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale.fx(119, 1): warning X4576: 'approximateBloomHorizPS': input parameter 'texcoord' semantic does not match vertex shader one
> vkShade err:   /opt/reshade-shaders/Shaders/crt-royale.fx(184, 1): warning X4576: 'applyComputedPhosphorMaskPS': input parameter 'texcoord' semantic does not match vertex shader one
> zsh: segmentation fault (core dumped)  ENABLE_VKSHADE=1 vkcube
> ```
> 
> So it looks like, at the very least, use of this shader will have to wait until #6 is taken care of. Unfortunately, updating the ReShade version is likely going to require a significant refactor of vkShade's code as well, so it will probably be some time before it's all sorted out.
> 
> As for your preset question, presets are standard ReShade presets, which are in the [INI file format](https://docs.fileformat.com/system/ini/). Often you will be able to find ready-to-go presets on the ReShade forums, or other sites such as NexusMods. Usually an individual preset is made for a specific game.
> 
> A fairly basic example looks like this:
> 
> ```ini
> PreprocessorDefinitions=
> Techniques=Curves,Clarity
> TechniqueSorting=Curves,Clarity
> 
> [Clarity.fx]
> ClarityBlendIfDark=50
> ClarityBlendIfLight=205
> ClarityBlendMode=0
> ClarityDarkIntensity=0.000000
> ClarityLightIntensity=0.000000
> ClarityOffset=50.000000
> ClarityRadius=4
> ClarityStrength=0.500000
> ClarityViewBlendIfMask=0
> ClarityViewMask=0
> 
> [Curves.fx]
> Contrast=0.650000
> Formula=1
> Mode=0
> ```
> 
> The only required key-value pair is `TechniquesSorting`, which is how vkShade knows which shaders to load. The shader names that go in this field can be kind of a "gotcha", as they don't necessarily match the shader file name, they actually use the **technique name** which can be found in the shader's source code.
> 
> The sections below are how you actually configure each shader. The heading (`[Clarity.fx]` for example) corresponds directly to the file name of the shader. The key-value pairs underneath the heading correspond directly to the shader **uniforms**, which is just the technical term for a variable when dealing with shaders. You can also find these in the source code, and probably in the shader's documentation as well.
> 
> You don't _have_ to configure the uniforms, but generally you will want to as the default settings are often either way too strong, or barely noticeable at all.

Alright, thank you so much for the information, I will wait until that issue is dealt with so I can began re-testing, also thank you for explaining to me how presets work, I werent able to find any information about it before!!

**Comment by ralgar** [comment]
No problem! As far as I can see there isn't any [official documentation](https://www.pcgamingwiki.com/wiki/ReShade) on ReShade presets at all, which is rather surprising.

Thanks for bringing it to my attention, I'll set up a Wiki for vkShade and add some basic info about configuring presets. :smiley:

**Comment by AmyRoxwell** [comment]
> No problem! As far as I can see there isn't any [official documentation](https://www.pcgamingwiki.com/wiki/ReShade) on ReShade presets at all, which is rather surprising.

Huh, weird, you would expect to at least be something :thinking: 

> Thanks for bringing it to my attention, I'll set up a Wiki for vkShade and add some basic info about configuring presets. 😃

That sounds amazing, this will surely help people that are newbies in all of these of the presets and stuff, again, thank you so much!!
