### ISSUE TITLE
Point releases for packaging

### ISSUE THREAD

**Issue by xolophreny** [ralgar/vkShade#21]
Hi! Quite interested in this project as a successor to vkBasalt in my use case, and would also like to package it for Void Linux. However, Void strongly recommends only packaging software that has point releases, to explicitly indicate that the developer approved this version of the software for public use.

So would like to bring that up - if you feel like vkShade is useable enough to deserve a point release at all at this stage, having them would be appreciated!
The readme also has a "v0.1.0" badge thing, so I thought there was such a release, but doesn't seem to be the case.

Excited for the future of the project, thanks!

**Comment by ralgar** [comment]
There is a git tag `v0.1.0` available, which is what the badge tracks. It's not a binary release (those will come later), but it is a point release of the source code. Github will also let you download an archive of it.

Anyone trying to use this project should be using that tag, as the `main` branch isn't necessarily stable.

I wouldn't really suggest packaging this yet. I basically consider it to be alpha software still. It does work, but it's far from feature complete and there's a good chance it won't work for your use case. When I consider it ready I'll make a proper v1.0.0 release.

I'm going to update the README to make note of this, and probably change the tag name to append `-alpha` to it as well.

I am committed to this project long term, but in the short term it will be a bit of a slow start unfortunately. I'm basically planning to refactor everything.

**Comment by xolophreny** [comment]
Oh, right, tags exist, thank you!

And fair enough, I appreciate your response and commitment. Best of luck!

**Comment by ralgar** [comment]
I've updated the tag and README to better reflect the project's alpha status. Thanks!
